apiVersion: apps/v1
kind: Deployment
metadata:
  name: sutdent-reg-webapp
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: studentregweabapp
  template:
    metadata:
      labels:
        app: studentregweabapp
    spec:
      containers:
      - name: studentregweabapp
        image: 775694652978.dkr.ecr.ap-south-1.amazonaws.com/student-reg-webapp:22
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /student-reg-webapp/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /student-reg-webapp/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5  