apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studentregweabapp-ingress
  namespace: test-ns
spec:
  ingressClassName: nginx
  rules:
  - host: studentreg.rushiitechnologies.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sutdent-reg-webapp-svc
            port: 
              number: 80
